# 开发环境配置文件
server:
  port: 8060

spring:
  application:
    name: ehcache-demo
  datasource:
    url: jdbc:mysql://localhost:3306/cachetest?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:



