# 开发环境配置文件
server:
  port: 8020

spring:
  application:
    name: business-center
  datasource:
    url: jdbc:mysql://localhost:3306/aiops?useUnicode=true&useSSL=false&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:



